from scrapinghub import ScrapinghubClient

apikey = '11befd9da9304fecb83dfa114d1926e9'
client = ScrapinghubClient(apikey)
project = client.get_project(252342)

for job in list(project.jobs.iter_last(spider='javname', state='finished')):
    javjob = job

print(javjob['key'])
job = project.jobs.get(javjob['key'])

namelist = []
namelist.append('秋山祥子')
namelist.append('天海つばさ')
namelist.append('友田彩也香')
namelist.append('麻倉憂')
namelist.append('瑠川リナ')
namelist.append('このは')
namelist.append('羽月希')
namelist.append('椎名みくる')
namelist.append('上原結衣')
namelist.append('早乙女らぶ')
namelist.append('葵司')
namelist.append('SARAH')
namelist.append('佐藤遥希')
namelist.append('小島みなみ')
namelist.append('上原亚衣')
namelist.append('若菜亜衣')
namelist.append('南梨央奈')
namelist.append('鶴田加奈')
namelist.append('丘咲エミリ')
namelist.append('愛内希')
namelist.append('初美沙希')
namelist.append('木村つな')
namelist.append('西野翔')
namelist.append('稲葉ゆい')
namelist.append('Rio')
namelist.append('つぼみ')
namelist.append('大橋未久')
namelist.append('板垣あずさ')
namelist.append('希志あいの')
namelist.append('瀬名あゆむ')
namelist.append('石原莉奈')
namelist.append('波多野结衣')
namelist.append('水菜丽')
namelist.append('黒木いちか')
namelist.append('希崎ジェシカ')
namelist.append('藤井シェリー')
namelist.append('藤崎セシル')
namelist.append('吉泽明步')
namelist.append('岩佐あゆみ')
namelist.append('初芽里奈')
namelist.append('みなともも')
namelist.append('绀野光')
namelist.append('樱由罗')
namelist.append('佳苗るか')
namelist.append('尾上若葉')
namelist.append('麻生希')
namelist.append('あべみかこ')
namelist.append('泷泽萝拉')
namelist.append('浜崎真緒')
namelist.append('Abigaile Johnson')
namelist.append('桜瀬奈')
namelist.append('きみと歩美')
namelist.append('古川伊织')
namelist.append('德田重男')
namelist.append('吉川あいみ')
namelist.append('入江愛美')
namelist.append('蒼乃かな')
namelist.append('保坂えり')
namelist.append('茜あずさ')
namelist.append('有本紗世')
namelist.append('白石茉莉奈')
namelist.append('饭冈加奈子')
namelist.append('葉山めい')
namelist.append('伊東紅')
namelist.append('希島あいり')
namelist.append('川村まや')
namelist.append('青井いちご')
namelist.append('逢坂はるな')
namelist.append('橋本涼')
namelist.append('裕木まゆ')
namelist.append('渡辺もも')
namelist.append('佐々木玲奈')
namelist.append('宮崎あや')
namelist.append('土屋あさみ')
namelist.append('柚月あい')
namelist.append('桃谷繪里香')
namelist.append('小川めるる')
namelist.append('天使もえ')
namelist.append('西田カリナ')
namelist.append('佐倉絆')
namelist.append('小波風')
namelist.append('ステイシー')
namelist.append('早乙女ゆい')
namelist.append('なごみ')
namelist.append('Gina Gerson')
namelist.append('みなみ愛星')
namelist.append('彩乃なな')
namelist.append('谷田部和沙')
namelist.append('市川まさみ')
namelist.append('葉山美空')
namelist.append('宮内栞')
namelist.append('長谷川るい')
namelist.append('青島かえで')
namelist.append('逢月はるな')
namelist.append('みなみもえ')
namelist.append('三上悠亜')
namelist.append('木下麻季')
namelist.append('橋本怜奈')
namelist.append('園田みおん')
namelist.append('長谷川モニカ')
namelist.append('跡美しゅり')
namelist.append('白桃心奈')
namelist.append('皆野あい')
namelist.append('アメリア・イヤハート')
namelist.append('桃乃木かな')
namelist.append('RION')
namelist.append('椎名そら')
namelist.append('向井藍')
namelist.append('橋本ありな')
namelist.append('井浦沙織')
namelist.append('南真菜果')
namelist.append('あおいれな')
namelist.append('琴羽雫')
namelist.append('来栖みさ')
namelist.append('斉藤みゆ')
namelist.append('今宮いずみ')
namelist.append('緒沢くるみ')
namelist.append('水稀みり')
namelist.append('宮沢ゆかり')
namelist.append('高桥圣子')
namelist.append('姫川ゆうな')
namelist.append('戸田真琴')
namelist.append('栄川乃亜')
namelist.append('もりの小鳥')
namelist.append('佐々木ゆう')
namelist.append('星乃ゆづき')
namelist.append('真田美樹')
namelist.append('久野せいな')
namelist.append('凰かなめ')
namelist.append('桃園みらい')
namelist.append('熊倉しょうこ')
namelist.append('雛形くるみ')
namelist.append('早乙女夏菜')
namelist.append('白咲はる')
namelist.append('椎奈さら')
namelist.append('月野ゆりあ')
namelist.append('きみかわ結衣')
namelist.append('明里つむぎ')
namelist.append('今井パオラ')
namelist.append('君色花音')
namelist.append('北川レイラ')
namelist.append('水トさくら')
namelist.append('一乃瀬るりあ')
namelist.append('ひなた澪')
namelist.append('桜空もも')
namelist.append('双葉良香')
namelist.append('藤波さとり')
namelist.append('小鳥遊みやび')
namelist.append('宝生リリー')

for name in namelist:
    filters = [("name", "=", [name])]
    #print(job.items.list(count=1, filter=filters))
    for item in job.items.iter(count=1, filter=filters):
        print(item['href'])
